In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.1'

In [6]:
# list, array
lst ={1,2,3,4,5,5,6,6}
arr = np.array(lst)

In [7]:
print(lst)

{1, 2, 3, 4, 5, 6}


In [8]:
import numpy as np 
arr =np.linespace(91,10,5)


AttributeError: module 'numpy' has no attribute 'linespace'

In [5]:
#id array convert into 2d array
arr =np.arrange(0,30)
arr 

AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
arr.reshape(5,6)

NameError: name 'arr' is not defined

In [7]:
arr =np.random.randit(1,5,9)
arr

AttributeError: module 'numpy.random' has no attribute 'randit'

In [9]:
arr =np.random.random(1)
arr

array([0.65851447])

In [11]:
arr =np.random.random((5,10))
arr

array([[0.04629795, 0.87854477, 0.20113979, 0.27886425, 0.35258248,
        0.07031613, 0.26094162, 0.07464313, 0.20418798, 0.01034492],
       [0.07050953, 0.57544085, 0.9159627 , 0.32693078, 0.06575781,
        0.05457552, 0.84821115, 0.35079592, 0.1001232 , 0.41569462],
       [0.15406743, 0.45697562, 0.55054936, 0.21210514, 0.23417524,
        0.34637593, 0.84561375, 0.0063775 , 0.53657786, 0.97482125],
       [0.33545089, 0.80654902, 0.68277013, 0.93587414, 0.56036713,
        0.25234513, 0.50625768, 0.27755805, 0.26062797, 0.88885787],
       [0.37566869, 0.89298673, 0.88485202, 0.84631166, 0.31556898,
        0.87098706, 0.22808612, 0.92005689, 0.38244039, 0.81076638]])

In [12]:
arr =np.arange(60).reshape(12,5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44],
       [45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59]])

arr.shape
arr.size
arr.dtype
print()

In [15]:
print("shape of array",arr.shape)
print("size of array",arr.size)
print("date of type",arr.dtype)
print("number of dimesnion",arr.ndim)

shape of array (12, 5)
size of array 60
date of type int64
number of dimesnion 2


In [16]:
arr.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [17]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59])

In [19]:
arr.T

array([[ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55],
       [ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56],
       [ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47, 52, 57],
       [ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48, 53, 58],
       [ 4,  9, 14, 19, 24, 29, 34, 39, 44, 49, 54, 59]])

In [20]:
arr =np.arange(30)

In [21]:
arr[20]

np.int64(20)

In [23]:
arr[12]

np.int64(12)

In [25]:
arr[1]

np.int64(1)

In [26]:
arr[1,3:5]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [27]:
arr[0:5,1:2]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [29]:
arr[11]

np.int64(11)

In [30]:
arr[11][-1]

IndexError: invalid index to scalar variable.

In [31]:
np.array(np.arrange(224)).reshape()

AttributeError: module 'numpy' has no attribute 'arrange'

In [32]:
arr.ndim,arr.shape,arr.size

(1, (30,), 30)

In [35]:
arr{o,2:}

SyntaxError: invalid syntax (1078481257.py, line 1)

In [36]:
arr[0,3:5]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [37]:
arr[-1]

np.int64(29)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [39]:
arr[0,2:,2]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [ ]:
arr[0,1,1] = 1000

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [46]:
arr1 = np.array([1,2,3,5])
arr2 = np.array([1,6,3,5])

In [48]:
# arr1+arr2
# arr1*arr2
arr1-arr2

array([ 0, -4,  0,  0])